# Documentation
# https://github.com/yonaskolb/XcodeGen/blob/master/Docs/ProjectSpec.md

include:
  - targetTemplate.yml

name: "HeavyLog"

options:
  bundleIdPrefix: "sebastian-staszczyk"
  groupSortPosition: "top"
  platform: "iOS"
  deploymentTarget:
    iOS: "14.0"

localPackages:
  - "./Packages/HeavyLogCoreData"
  - "./Packages/Shared"

configs:
  Dev Debug: debug
  Unmerged Debug: debug
  AppStore Debug: debug
  Dev Release: release
  Unmerged Release: release
  AppStore Release: release

targets: 
  HeavyLog:
    scheme:
      testTargets:
        - HeavyLog
        - name: "HeavyLog"
          parallelizable: true
      gatherCoverageData: true
    templates:
      - HeavyLog
    dependencies:
      - package: "HeavyLogCoreData"
      - package: "Shared"

  HeavyLogTests:
    type: "bundle.unit-test"
    platform: "iOS"
    sources:
      - path: "HeavyLogTests"
    scheme:
      testTargets:
        - HeavyLogTests
      gatherCoverageData: true
      configVariants:
        - Dev
    dependencies:
      - target: "HeavyLog"


targetTemplates:
  HeavyLog:
    platform: "iOS"
    type: "application"
    sources: ["HeavyLog"]
    scheme:
      configVariants: ["Unmerged"]

