# Documentation
# https://github.com/yonaskolb/XcodeGen/blob/master/Docs/ProjectSpec.md

name: "HeavyLog"
options:
  createIntermediateGroups: true
  usesTabs: false
  indentWidth: 4
  tabWidth: 4
  bundleIdPrefix: "de.number42"
  groupSortPosition: "top"

localPackages:
  - ./Packages/HeavyLogCoreData
  - ./Packages/Shared

targets: 
  HeavyLog:
    type: "application"
    platform: "iOS"
    deploymentTarget: "14.0"
    sources:
      - path: "HeavyLog"
    dependencies:
      - package: HeavyLogCoreData
      - package: Shared
  HeavyLogTests:
    type: "bundle.unit-test"
    platform: "iOS"
    deploymentTarget: "14.0"
    sources:
      - path: "HeavyLogTests"
    dependencies:
      - target: "HeavyLog"



